-- PROJECT CODEX: DATABASE SCHEMA (MVP)
-- Target: Supabase (PostgreSQL)

-- 1. PROFILES (Extends Supabase Auth)
-- Stores user-specific settings and plan levels.
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    organization_name TEXT,
    avatar_url TEXT,
    plan_level TEXT DEFAULT 'free', -- 'free', 'pro', 'enterprise'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BOOKS (The Parent Entity)
-- Represents the "Digital Asset" created from a PDF.
CREATE TABLE books (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL, -- URL-friendly ID: project-codex.io/view/slug
    description TEXT,
    original_pdf_url TEXT, -- Link to the raw file in Supabase Storage
    
    -- Status Management for Asynchronous Parsing
    job_status TEXT DEFAULT 'idle', -- 'idle', 'queued', 'parsing', 'generating_assets', 'success', 'failed'
    error_log TEXT, -- Stores error messages if the parser fails
    
    is_published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CODEX_MANIFESTS (The "Single Source of Truth")
-- Stores the actual JSON structure generated by the Python Parser.
CREATE TABLE codex_manifests (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    book_id UUID REFERENCES books(id) ON DELETE CASCADE UNIQUE NOT NULL,
    manifest_data JSONB NOT NULL, -- The "sample_codex_manifest.json" structure
    parser_version TEXT, -- Tracks which version of the Python Engine was used
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- 4. WIDGET_REGISTRY
-- Tracks interactive elements (Videos, Calculators) added via the Flutter Editor.
CREATE TABLE widgets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    book_id UUID REFERENCES books(id) ON DELETE CASCADE NOT NULL,
    block_id TEXT NOT NULL, -- Refers to the "id" in the JSON structure
    type TEXT NOT NULL, -- 'youtube_embed', 'roi_calculator', etc.
    config JSONB, -- Widget-specific settings
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ANALYTICS_SNAPSHOTS (MVP Version)
CREATE TABLE analytics_logs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    book_id UUID REFERENCES books(id) ON DELETE CASCADE,
    event_type TEXT, -- 'view', 'pwa_install', 'widget_click'
    user_agent TEXT,
    geo_country TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES FOR PERFORMANCE
CREATE INDEX idx_books_owner ON books(owner_id);
CREATE INDEX idx_books_slug ON books(slug);
CREATE INDEX idx_books_status ON books(job_status);
CREATE INDEX idx_manifest_data ON codex_manifests USING GIN (manifest_data);

-- ROW LEVEL SECURITY (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE codex_manifests ENABLE ROW LEVEL SECURITY;

-- POLICIES
CREATE POLICY "Users can manage their own books"
ON books FOR ALL
USING (auth.uid() = owner_id);

CREATE POLICY "Public can view published books"
ON books FOR SELECT
USING (is_published = TRUE);